### ISSUE TITLE
Code examples in ledger3.html show as white-on-white when the browser is configured for dark mode 

### ISSUE THREAD

**Issue by Gumnos** [ledger/ledger.github.io#99]
I'm not sure when this started happening, and I can't find the `ledger3.html` source in this sub-tree, but the [documentation page](https://ledger-cli.org/doc/ledger3.html) brings in a `style.css` file from `gnu.org` (possibly an Emacs-to-web type artifact?) where the `pre.example` blocks get styled with a hard-coded

    background-color: #f9f6ed;

This leads to unreadable white text on this mostly-white background.  It should likely be something like

    background-color: var(--highlight-code-background-color);

where that `--highlight-code-background-color` CSS variable does get correctly/adequately set in the

    @media (prefers-color-scheme: dark) {
      :root {…}

block.  If I select the text, it's there and visible as shown in this screenshot of the issue:

![Screenshot of the issue in question](https://github.com/user-attachments/assets/383d6594-626a-4afb-8944-02174cd8346f)

**Comment by afh** [comment]
Thanks for bringing this up, @Gumnos, I'll have a l👀k…

**Comment by Gumnos** [comment]
FWIW, my X environment is configured for dark-mode, so this manifests in both Firefox & Chromium. Amusingly, if I use `dillo` or `lynx` as my browser, the whole thing displays fine :laughing:

**Comment by afh** [comment]
While the underlying issue is fixed, another issue regarding the deployment has appeared. I'm looking into it.

**Comment by afh** [comment]
Alright, might have been a caching issue… The fix appears to be properly deployed for me.
@Gumnos mind giving it another try?
Be sure that https://ledger-cli.org/css/darkmode.css contains the following CSS:

```css
pre.example-preformatted {
  /* Override hard-coded background color from gnu manual.css with dark/light mode variant */
  background-color: var(--highlight-code-background-color) !important; }
```

If it doesn't I assume somewhere some cache hasn't been invalidated yet.
